domain = "architecture"
schema_version = 1

[component.api]
depends_on = ["ir", "media", "platforms", "projects", "security", "settings"]

[component.cli]
depends_on = ["api", "ir"]

[component.ir]
depends_on = []

[component.mcp]
depends_on = ["cli"]

[component.media]
depends_on = ["ir"]

[component.platforms]
depends_on = ["ir", "media", "projects", "security", "settings"]

[component.projects]
depends_on = ["ir", "media"]

[component.security]
depends_on = ["ir"]

[component.settings]
depends_on = ["ir"]

[component.ui_web]
depends_on = ["ir", "ui_general"]

[component.ui_extension]
depends_on = ["ir", "ui_general"]

[component.ui_general]
depends_on = ["ir"]

[component.service]
depends_on = ["api", "ir", "mcp", "platforms", "security", "settings"]
